const COMPUTE_SKILL_ID = 'remote-compute-ssh'
const COMPUTE_SKILL_DIRECTORY = `os-${COMPUTE_SKILL_ID}`
const COMPUTE_ENV_SETUP_SKILL_ID = 'compute-env-setup'
const COMPUTE_ENV_SETUP_SKILL_DIRECTORY = `os-${COMPUTE_ENV_SETUP_SKILL_ID}`

export {
  COMPUTE_ENV_SETUP_SKILL_DIRECTORY,
  COMPUTE_ENV_SETUP_SKILL_ID,
  COMPUTE_SKILL_DIRECTORY,
  COMPUTE_SKILL_ID
}
